version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "8001:5432"
    environment:
      POSTGRES_PASSWORD: "0000"
      POSTGRES_USER: postgres
      POSTGRES_DB: shop